version: '3.7'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '5432:5432'

    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=TravelShopDB
      - MYSQL_USER=TravelShop
      - MYSQL_PASSWORD=BuyTour