version: "3.7"
services:
  node:
    image: "node:16-alpine"
    build:
      context: ./gate-simulator
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./gate-simulator:/home/node/app
    expose:
      - "9999"
    command: "npm start"



  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass


  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass